#define N_tel 2
#define N_cook 2
#define N_oven 10
#define N_deliverer 10
#define T_orderLow 1
#define T_orderHigh 5
#define N_orderLow 1
#define N_orderHigh 5
#define P_m 0.35
#define P_p 0.25
#define P_s 0.4
#define T_paymentLow 1
#define T_paymentHigh 3
#define P_fail 0.05
#define C_m 10
#define C_p 11
#define C_s 12
#define T_prep 1
#define T_bake 10
#define T_pack 1
#define T_delLow 5
#define T_delHigh 15